language: ruby
cache: bundler

rvm:
  - 2.3

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "echo '--colour' > ~/.rspec"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
